# Site settings
title: Mark Taylor
email: marktaycon@googlemail.com
description: "The thoughts and ramberlings of a Java developer"
baseurl: ""
url: "mgt6/mgt6.github.com"
twitter_username: marktaycon
github_username:  mgt6

# Build settings
markdown: kramdown
permalink: pretty
